# To run: conda env create -f environment.yml
# pip install wandb
name: instance_nerf
channels:
    - conda-forge
dependencies:
    - python==3.9
    - cudatoolkit=11.3
    - pytorch==1.12.1 
    - torchvision==0.13.1
    - pandas
    - tqdm
    - wandb
